pipeline {
    agent any

    environment {
        AWS_REGION = 'us-west-3'
        S3_BUCKET = 'task-manager-rm'
        CLOUDFRONT_DISTRIBUTION_ID = 'E2SOKDTZQC348S'
    }

    stages {

        stage('checkout') {
            steps {
                git credentialsId: 'frontend-credentials', url: 'https://github.com/Kameshjustin/Devops-taskmanager-mern.git'
            }
        }

        stage('install dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                withCredentials([file(credentialsId: 'taskmanager-rm', variable: 'ENV_PROD')]) {
                    dir('frontend') {
                        sh '''
                        cp $ENV_PROD .env.production
                        npm run build
                        '''
                    }
                }
            }
        }

        stage('Deploy to S3') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'taskmanager0123']]) {
                    sh """
                    /usr/local/bin/aws s3 sync frontend/build/ s3://${S3_BUCKET} --delete
                    """
                }
            }
        }

        stage('Invalidate CloudFront Cache') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'taskmanager0123']]) {
                    sh """
                    /usr/local/bin/aws cloudfront create-invalidation \
                    --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
                    --paths '/*'
                    """
                }
            }
        }
    }
    
    post {
        success {
            echo "Deployment Successful! Your app is live........"
        }
        failure {
            echo "Pipeline failed. Check the logs...................."
        }
    }

}


